on:
  push:
    branches:
      - main
name: 🚀 Deploy website To Production
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🧰 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: 🧱 Install Dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Optimize
        run: php artisan optimize

      - name: 📂 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 21
          server-dir: public_html/
          exclude: |
            **/vendor/**
            **/.git/**
            **/.github/**
